[tool.black]
line-length = 120
target-version = ['py38']
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.isort]
known_third_party = []
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 120


[tool.flakehell]
format='grouped'
show_source = true
exclude = ['.git','.venv','__pycache__','build','dist']
max_complexity = 10
max_line_length = 120

[tool.flakehell.plugins]
pycodestyle = ['+*', '-E203', '-W503']
pyflakes = ['+*']

cohesion = ['+*']
dlint = ['+*']
darglint = ['+*']
# enable everything that starts from `flake8-`
'flake8-*' = ['+*']
pep8-naming = ['+*']
