version: 2
jobs:
  build:
    docker:
      - image: cimg/python:3.8
        environment:
          PIPENV_VENV_IN_PROJECT: true
    steps:
      - checkout
      - restore_cache:
          key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
      - run:
          command: |
            pipenv install --dev
      - save_cache:
          key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - "venv"
      - restore_cache:
          key: deps9-{{ .Branch }}-{{ checksum ".pre-commit-config.yaml" }}
      - run:
          command: |
            pipenv run pre-commit run --all-files
      - save_cache:
          key: deps9-{{ .Branch }}-{{ checksum ".pre-commit-config.yaml" }}
          paths:
            - "~/.cache/pre-commit"
      - run:
          command: |
            pipenv run python -m unittest discover -v
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
          destination: tr1
